<?php 
class Mork_Common_Commons
{
	const VERSION_1_0 = "1.0";
	
	// ERRORS
	const JSON_PARSE_ERROR = 'JSON_PARSE_ERROR';
	const INVALID_REQUEST_ERROR = 'INVALID_REQUEST_ERROR';
	const METHOD_NOT_FOUND_ERROR = 'METHOD_NOT_FOUND_ERROR';
	const INTERNAL_ERROR = 'INTERNAL_ERROR';
	const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
	const APPLICATION_ERROR = 'APPLICATION_ERROR';
}
