<?php 
class Mork_Common_Commons
{
	const VERSION_1_0 = "1.0";
	
	// ERRORS
	const INVALID_JSON_ERROR = 'INVALID_JSON_ERROR';
	const INVALID_REQUEST_ERROR = 'INVALID_REQUEST_ERROR';
	const METHOD_NOT_FOUND_ERROR = 'METHOD_NOT_FOUND_ERROR';
	const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
	const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
	const APPLICATION_ERROR = 'APPLICATION_ERROR';
}
